language: python
sudo: false
dist: trusty
python: 3.6
cache:
  directories:
  - $HOME/.pip/wheels

before_install:
  - python --version
  - virtualenv --version
  - pip --version
  - uname -a
  - lsb_release -a

install:
  - mkdir -p ~/.pip
  - cp ci/pip.conf ~/.pip/pip.conf
  - pip install -U wheel setuptools tox

script:
  - tox
